[managers.portage]
items = [
	"x11-base/xorg-server",
	"x11-base/xorg-drivers",
	"media-sound/pulseaudio",
	"media-sound/pavucontrol",
	"media-sound/spotify",
	"media-video/pipewire",
	"gui-wm/hyprland",
	"x11-terms/alacritty",
	"www-client/firefox",
	"app-misc/fastfetch",
	"net-misc/dhcpcd",
	"net-misc/networkmanager",
	"gui-apps/wofi",
	"net-misc/tigervnc",
	"net-misc/tigervnc-xorg-module",
	"gui-apps/wayvnc",
	"x11-wm/i3",
	"x11-misc/i3status",
	"x11-misc/dmenu",
	"x11-wm/awesome",
	"media-gfx/feh",
	"gnome-base/gnome-light",
]

[managers.portage-guru]
items = [
	"gui-libs/xdg-desktop-portal-hyprland"
]

[managers.systemd-services]
items = [
	"gdm"
]
