[managers.portage]
items = [
	"x11-base/xorg-server",
	"x11-base/xorg-drivers",
	"media-sound/pulseaudio",
	"media-sound/pavucontrol",
	"media-video/pipewire",
	"gui-wm/hyprland",
	"x11-terms/alacritty",
	"www-client/firefox",
	"app-misc/fastfetch",
	"net-misc/dhcpcd",
	"net-misc/networkmanager",
	"gui-apps/wofi",
]

[managers.portage-guru]
items = [
	"gui-libs/xdg-desktop-portal-hyprland"
]
