[managers.portage]
items = [
	"dev-lang/zig",
	"net-libs/nodejs",
	"dev-util/github-cli",
	"sys-apps/arch-chroot",
	"dev-lang/php",
	"www-servers/nginx",
	"dev-db/mysql",
	"app-editors/vscode",
]

[managers.dispatch-interactive-config]
items = [
	"dev-db/mysql",
]

[managers.systemd-enable-now]
items = [
	"nginx",
	"php-fpm@8.2",
	"mysqld",
]
