[managers.portage-emulation]
items = [
	"app-emulation/libvirt",
	"app-emulation/qemu",
	"app-emulation/virt-manager",
]

[managers.systemd-enable-now]
items = [
	"virtlogd",
	"virtlockd",
	"libvirtd"
]
