[managers.portage]
items = [
	"app-misc/hello",
	"app-text/tree",
	"gui-apps/grim",
	"gui-apps/slurp",
	"sys-process/htop",
	"sys-fs/dosfstools",
]

[managers.portage-andromeda]
items = [
	"app-misc/cutefetch",
]
