[managers.portage]
items = [
	"app-misc/hello",
	"app-text/tree",
	"gui-apps/grim",
	"gui-apps/slurp",
	"sys-process/htop",
	"sys-fs/dosfstools",
	"app-portage/genlop",
	"app-shells/starship",
	"app-shells/zoxide",
	"sys-apps/eza",
	"sys-apps/bat",
]

[managers.portage-andromeda]
items = [
	"app-misc/cutefetch",
	"app-misc/open-repo"
]
