add = "sudo emerge --verbose #:? --ask" # Example: sudo apt install #:?
remove = "sudo emerge -cav #:?" # Example: sudo apt remove #:?
plural_name = "portage emulation pkgs"
hook_name = "portage_emulation"

[config]
many_args = true
