add = "sudo emerge -v #:?"
remove = "sudo emerge -cv #:?"
sync = "sudo emerge --sync"
upgrade = "sudo emerge -vuDN @world"

plural_name = "portage pkgs"
hook_name = "portage"

[config]
many_args = true
