# Generated via scripts/CreatePortageRepoManager

add = "sudo emerge -v #:?"
remove = "sudo emerge -cv #:?"
plural_name = "portage guru-repo pkgs"
hook_name = "portage_guru"

[config]
many_args = true
