# Generated via scripts/CreatePortageRepoManager

add = "sudo emerge --verbose #:? --ask"
remove = "sudo emerge -cav #:?"
sync = "sudo emerge --sync"
upgrade = "sudo emerge -avuDN @world"

plural_name = "portage andromeda-repo pkgs"

hook_name = "portage_andromeda"

[config]
many_args = true
