# Generated via scripts/CreatePortageRepoManager

add = "sudo emerge -v #:?"
remove = "sudo emerge -cv #:?"
plural_name = "portage andromeda-repo pkgs"
hook_name = "portage_andromeda"

[config]
many_args = true
