add = "sudo emerge --verbose #:? --ask" # Example: sudo apt install #:?
remove = "sudo emerge -cav #:?" # Example: sudo apt remove #:?
plural_name = "portage guru-repo pkgs"
hook_name = "portage_guru"

[config]
many_args = true
