#!/usr/bin/env bash

cd ~/.config/rebos

. ~/.config/rebos/hooks/common/utils.sh

global_system_files="$HOME/.config/rebos/system_files"
system_files="$global_system_files/$HOSTNAME"
preferred_timezone="America/Caracas"

log_info "Setting zoneinfo to ${preferred_timezone}"

sudo ln -svf /usr/share/zoneinfo/${preferred_timezone} /etc/localtime
sudo hwclock --systohc

log_info "Editor = vim"

sudo eselect editor set vim

system_cache="$HOME/.cache/rebos"

test -d "$system_cache" || mkdir -pv "$system_cache"

if ! [[ -f "$system_cache/genfstab" ]]; then
	touch "$system_cache/genfstab"
	log_info "Generating fstab"
	sudo genfstab -U / | sudo tee /etc/fstab
fi

sudo systemctl daemon-reload

append_to() {
	echo "${2}" | sudo tee -a "${1}" 2>&1 > /dev/null
}

should_run_grub_mkconfig=0

if [[ "$(cat /etc/default/grub | grep GRUB_DISABLE_OS_PROBER)" == "" ]]; then
	log_info "Enabling os prober for grub"
	append_to /etc/default/grub ""
	append_to /etc/default/grub "# Enable other oses detection"
	append_to /etc/default/grub "GRUB_DISABLE_OS_PROBER=false"
	should_run_grub_mkconfig=1
fi

if [[ "$(cat /etc/default/grub | grep GRUB_CMDLINE_LINUX | grep "zswap.enabled=1")" == "" ]]; then
	log_info "Enabling zswap in grub (permanently)"
	append_to /etc/default/grub ""
	append_to /etc/default/grub "# Enable zswap permanently"
	append_to /etc/default/grub 'GRUB_CMDLINE_LINUX="zswap.enabled=1 zswap.compressor=lz4"'

	log_info "Enabling zswap for this system (temporarily)"
	echo 1 | sudo tee /sys/module/zswap/parameters/enabled
	echo lz4 | sudo tee /sys/module/zswap/parameters/compressor

	should_run_grub_mkconfig=1
fi

test -d /boot/grub || \
	log_warning "Remember to install grub by using grub-install"

test -f /etc/hostname || \
	log_warning "Remember to set your hostname"

if [[ "$should_run_grub_mkconfig" == 1 ]]; then
	log_warninging "Rebuilding grub config"
	sudo grub-mkconfig -o /boot/grub/grub.cfg
fi

log_info "Copying config files"

config_files="$system_files/config_files"

cp -rvf "$config_files/.bashrc" ~/.bashrc
sudo cp -rvf "$config_files/.bashrc.root" /root/.bashrc

rsync -vah "$config_files/.config/" ~/.config

log_info "Synchronising system files"

root_files="$system_files/system_files"

for x in $root_files/*; do
	sudo rsync -vah $x /
done

log_info "Cleaning up"

cd ~/.config/rebos && find -type f -name \*.bak -delete

log_info "Success"
