#!/usr/bin/env bash

cd ~/.config/rebos

global_system_files="$HOME/.config/rebos/system_files"
system_files="$global_system_files/$HOSTNAME"
preferred_timezone="America/Caracas"

echo "* Setting zoneinfo to ${preferred_timezone}"

sudo ln -svf /usr/share/zoneinfo/${preferred_timezone} /etc/localtime
sudo hwclock --systohc

echo
echo "* Editor = vim"

sudo eselect editor set vim

system_cache="$HOME/.cache/rebos"

test -d "$system_cache" || mkdir -pv "$system_cache"

if ! [[ -f "$system_cache/genfstab" ]]; then
	touch "$system_cache/genfstab"
	sudo genfstab -U / | sudo tee /etc/fstab
fi

sudo systemctl daemon-reload

append_to() {
	echo "${2}" | sudo tee -a "${1}" 2>&1 > /dev/null
}

echo

if [[ "$(cat /etc/default/grub | grep GRUB_DISABLE_OS_PROBER)" == "" ]]; then
	echo "* Grub os detection"
	append_to /etc/default/grub "# Enable other oses detection"
	append_to /etc/default/grub "GRUB_DISABLE_OS_PROBER=false"
fi

test -d /boot/grub || \
	echo "warn: Remember to install grub by using grub-install and grub-mkconfig & remember to set your hostname"

echo
echo "* Copying config files"

config_files="$system_files/config_files"

cp -rvf "$config_files/.bashrc" ~/.bashrc
sudo cp -rvf "$config_files/.bashrc.root" /root/.bashrc

rsync -vah "$config_files/.config/" ~/.config

echo
echo "* Cleaning up"

cd ~/.config/rebos && find -type f -name \*.bak -delete
