#!/usr/bin/env bash

cd ~/.config/rebos

. ~/.config/rebos/hooks/common/utils.sh

if ! [[ -d /var/$USER ]]; then
	log_warning "Creating /var/$USER/.{config,local,cache}"
	mkdir -pv /var/$USER/.{config,local,cache}
	chown -R $USER:$USER /var/$USER

	declare -a items=(config local cache)

	for item in ${items[@]}; do
		if ! [[ -L "/home/$USER/.${item}" ]]; then
			log_info "Creating symlink to /var/$USER/.${item} into /home/$USER/.${item}"
			ln -sf /var/$USER/.${item} /home/$USER/.${item}
		fi
	done
fi

log_info "Changing profile if required"

# This only for hp-prodesk machine which is dev host, but also vms host.
if [[ "$HOSTNAME" == "hp-prodesk" ]]; then
	sudo eselect profile set default/linux/amd64/23.0/split-usr/desktop/gnome
fi

log_warning "Performing /etc/portage/repos.conf check"

test -d /etc/portage/repos.conf || sudo mkdir -pv /etc/portage/repos.conf

test -f /etc/portage/repos.conf/gentoo.conf || \
	sudo cp -rvf /usr/share/portage/config/repos.conf /etc/portage/repos.conf/gentoo.conf

global_system_files="$HOME/.config/rebos/system_files"
system_files="$global_system_files/$HOSTNAME"

log_info "Updating make.conf"

sudo cp -rvf "$system_files/make.conf" /etc/portage/make.conf

log_info "Updating pkgs configs"

pkgs_licenses="$system_files/skel/package.license"
pkgs_accept_keywords="$system_files/skel/package.accept_keywords"
pkgs_use="$system_files/skel/package.use"

copy_pkgs_conf() {
	test -d $1 || sudo mkdir -pv $1
	sudo cp -rvf $2/* $1
}

copy_pkgs_conf /etc/portage/package.license $pkgs_licenses
copy_pkgs_conf /etc/portage/package.accept_keywords $pkgs_accept_keywords
copy_pkgs_conf /etc/portage/package.use $pkgs_use

log_info "Success"
